languageCode: 'en-us'
disableKinds: [ 'RSS' ]
baseURL: https://shum.fyi
title: shum.fyi

minify:
  minifyOutput: true

markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  events: '/e/:filename/'
  items: '/i/:filename/'
  tags: '/t/:slug/'

params:
  description: Should Have Used Monero!
  keywords: 'shum,monero,should,have,used'
